# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

binary_search <- function(breaks, search, left_index) {
    .Call('epic_binary_search', PACKAGE = 'epic', breaks, search, left_index)
}

extract_sites <- function(start, end, site, return_index, min_sites) {
    .Call('epic_extract_sites', PACKAGE = 'epic', start, end, site, return_index, min_sites)
}

rowWhichMax <- function(m) {
    .Call('epic_rowWhichMax', PACKAGE = 'epic', m)
}

